# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Skysper
email: wtwpfwd0708@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  吴朋飞的个人博客，4年生.Net程序员，目前向跨平台技术转变和学习中.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://skysper.github.io" # the base hostname & protocol for your site

# Build settings
gems: [jekyll-paginate]

markdown: kramdown
kramdown:
  input: GFM       # use Github Flavored Markdown !important
exclude: ["Rakefile", "CNAME", "README.md","params.json"]
permalink: /:year/:month/:title
paginate: 10
paginate_path: "/page:num"
